// This file contains rules, that would cause errors / could cause unexpected behaviour

export const rules = {
  'use-isnan': ['error'],
  'constructor-super': ['error'],
  'for-direction': ['error'],
  'no-unsafe-finally': ['error'],
  'no-unsafe-negation': ['error'],
  'getter-return': ['error'],
  'no-setter-return': ['error'],
  'no-async-promise-executor': ['error'],
  'no-compare-neg-zero': ['error'],
  'no-dupe-args': ['error'],
  'no-dupe-class-members': ['error'],
  'no-dupe-else-if': ['error'],
  'no-dupe-keys': ['error'],
  'no-duplicate-case': ['error'],
  'no-duplicate-imports': ['warn'],
  'no-fallthrough': ['error'],
  'no-inner-declarations': ['error'],
  'no-irregular-whitespace': ['error'],
  'valid-typeof': ['error'],
  'no-new-symbol': ['error'],
  'no-unsafe-optional-chaining': ['error'],
  'no-undef': ['warn'],
  'no-this-before-super': ['error'],
  'no-sparse-arrays': ['error'],
  'no-prototype-builtins': ['error'],
  'no-obj-calls': ['error'],
  'no-misleading-character-class': ['error'],
  'no-loss-of-precision': ['error'],

  // regex
  'no-control-regex': ['error'],
  'no-empty-character-class': ['error'],
  'no-empty-pattern': ['error'],
  'no-invalid-regexp': ['error'],
  'no-useless-backreference': ['warn'],
}
