import { rules as style } from './style'

module.exports = {
  rules: Object.assign({
    'eqeqeq': ['warn'],
    'multiline-comment-style': ['warn', 'bare-block'],
    'no-extra-boolean-cast': ['warn'],
    'camelcase': ['error', { properties: 'never', ignoreDestructuring: false }],
    'new-parens': ['error', 'always'],

    'constructor-super': ['error'],
    'for-direction': ['error'],
    'getter-return': ['error'],
    'no-async-promise-executor': ['error'],
    'no-class-assign': ['error'],
    'no-compare-neg-zero': ['error'],
    'no-cond-assign': ['error'],
    'no-const-assign': ['error'],
    'no-constant-condition': ['error'],
    'no-control-regex': ['error'],
    'no-debugger': ['error'],
    'no-dupe-args': ['error'],
    'no-dupe-class-members': ['error'],
    'no-dupe-else-if': ['error'],
    'no-dupe-keys': ['error'],
    'no-duplicate-case': ['error'],
    'no-duplicate-imports': ['warn'],
    'no-empty-character-class': ['error'],
    'no-empty-pattern': ['error'],
    'no-ex-assign': ['error'],
    'no-fallthrough': ['error'],
    'no-func-assign': ['error'],
    'no-import-assign': ['error'],
    'no-inner-declarations': ['error'],
    'no-invalid-regexp': ['error'],
    'no-irregular-whitespace': ['error'],
    'no-loss-of-precision': ['error'],
    'no-misleading-character-class': ['error'],
    'no-new-symbol': ['error'],
    'no-obj-calls': ['error'],
    'no-prototype-builtins': ['error'],
    'no-self-assign': ['error'],
    'no-setter-return': ['error'],
    'no-sparse-arrays': ['error'],
    'no-this-before-super': ['error'],
    'no-undef': ['warn'],
    'no-unexpected-multiline': ['error'],
    'no-unreachable': ['warn'],
    'no-unsafe-finally': ['error'],
    'no-unsafe-negation': ['error'],
    'no-unsafe-optional-chaining': ['error'],
    'no-unused-vars': ['warn'],
    'no-useless-backreference': ['warn'],
    'use-isnan': ['error'],
    'valid-typeof': ['error'],
    'no-multi-assign': ['error'],
    'no-new-object': ['error'],
    'no-plusplus': ['error', { allowForLoopAfterthoughts: true }],
    'operator-assignment': ['warn', 'always'],
    'no-array-constructor': ['error'],
    'no-lonely-if': ['warn'],
    'no-mixed-operators': ['error', {
      groups: [
        ['%', '**'],
        ['%', '+'],
        ['%', '-'],
        ['%', '*'],
        ['%', '/'],
        ['/', '*'],
        ['&', '|', '<<', '>>', '>>>'],
        ['==', '!=', '===', '!=='],
        ['&&', '||'],
      ],
      allowSamePrecedence: false,
    }],
  }, style),
}
