
export const rules = {
  'semi': ['warn', 'never'],
  'semi-style': ['error', 'last'],
  'quotes': ['warn', 'single'],
  'jsx-quotes': ['warn', 'prefer-double'],
  'indent': ['warn', 2],
  'brace-style': ['warn', '1tbs', { allowSingleLine: true }],
  'quote-props': ['warn', 'consistent-as-needed'],
  'no-tabs': ['error'],
  'no-trailing-spaces': ['warn', { ignoreComments: true, skipBlankLines: true }],

  'keyword-spacing': ['warn', {
    before: true,
    after: true,
    overrides: {
      return: { after: true },
      throw: { after: true },
      case: { after: true },
    },
  }],
  'arrow-spacing': ['warn', { before: true, after: true }],
  'array-bracket-newline': ['warn', 'consistent'],
  'array-bracket-spacing': ['warn', 'never'],
  'block-spacing': ['warn', 'always'],
  'computed-property-spacing': ['warn'],
  'func-call-spacing': ['warn', 'never'],
  'generator-star-spacing': ['warn', { before: true, after: false }],
  'key-spacing': ['warn', { beforeColon: false, afterColon: true }],
  'object-curly-spacing': ['warn', 'always'],
  'rest-spread-spacing': ['warn', 'never'],
  'space-before-blocks': ['warn', 'always'],
  'space-in-parens': ['warn', 'never'],
  'space-infix-ops': ['warn', { int32Hint: false }],
  'switch-colon-spacing': ['warn', { after: true, before: false }],
  'template-curly-spacing': ['warn', 'always'],
  'template-tag-spacing': ['warn', 'always'],
  'eol-last': ['warn', 'always'],

  'comma-spacing': ['warn', { before: false, after: true }],
  'comma-dangle': ['warn', 'always-multiline'],
  'comma-style': ['warn', 'last', {
    exceptions: {
      ArrayExpression: false,
      ArrayPattern: false,
      ArrowFunctionExpression: false,
      CallExpression: false,
      FunctionDeclaration: false,
      FunctionExpression: false,
      ImportDeclaration: false,
      ObjectExpression: false,
      ObjectPattern: false,
      VariableDeclaration: false,
      NewExpression: false,
    },
  }],

  'function-call-argument-newline': ['warn', 'consistent'],
  'func-style': ['warn', 'declaration', { allowArrowFunctions: true }],

  'spaced-comment': ['warn', 'always', { markers: ['/'] }],

  'function-paren-newline': ['warn', 'consistent'],
  'implicit-arrow-linebreak': ['error', 'beside'],
  'linebreak-style': ['error', 'unix'],
  'lines-between-class-members': ['warn', 'always', { exceptAfterSingleLine: true }],
  'newline-per-chained-call': ['error', { ignoreChainWithDepth: 4 }],
  'no-mixed-spaces-and-tabs': ['warn'],
  'no-spaced-func': ['warn'],
  'no-whitespace-before-property': ['warn'],
  'nonblock-statement-body-position': ['warn', 'beside', { overrides: {} }],
  'object-curly-newline': ['warn', { multiline: true }],
  'object-property-newline': ['warn', { allowAllPropertiesOnSameLine: true }],
  'semi-spacing': ['error', { before: false, after: true }],
  'space-before-function-paren': ['warn', {
    anonymous: 'always',
    named: 'never',
    asyncArrow: 'always',
  }],
  'space-unary-ops': ['warn', {
    words: true,
    nonwords: false,
  }],
}
