name: lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: pnpm/action-setup@v2
     - uses: actions/setup-node@v3
       with:
         node-version: 18
         cache: pnpm

     - name: Install & build
       run: pnpm i && pnpm build

     - name: Lint
       run: pnpm lint
